language: clojure
dist: trusty
services:
    - redis-server
before_install:
    - sudo apt-get install nodejs
install:
    - lein cljsbuild once 
env:
    matrix:
        - TEST_CMD='lein test'
        - TEST_CMD='lein bench output --data-structure fractal -- --data-structure b-tree -- --data-structure sorted-set'
        - TEST_CMD='lein bench output --delete-pattern forward -- --delete-pattern reverse -- --delete-pattern shuffle -- --delete-pattern zero'
        - TEST_CMD='node ./test_node.js'
script: $TEST_CMD
